# Generated by Django 4.2.5 on 2023-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdesheetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdeproblems',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
